POST http://localhost:3000/dps HTTP/1.1
Content-Type: application/json

{
    "CharacterName" : "Xiuuu",
    "ILevel" : 250,
    "DamagePerSecond": 100000
}
###
POST http://localhost:3000/healer HTTP/1.1
Content-Type: application/json

{
    "CharacterName" : "Matsumoto",
    "ILevel" : 250,
    "HealingPerSecond": 12000
}
###
GET http://localhost:3000/healer HTTP/1.1
Content-Type: application/json
###
POST http://localhost:3000/tank HTTP/1.1
Content-Type: application/json

{
    "CharacterName" : "Bartuukk",
    "ILevel" : 100,
    "armour": 1
}
###
GET http://localhost:3000/Tank/626edd8cfb65edcc5da8a16d HTTP/1.1
Content-Type: application/json
###
GET http://localhost:3000/healer/healing/10000 HTTP/1.1
Content-Type: application/json
###
GET http://localhost:3000/tank/armour/100 HTTP/1.1
Content-Type: application/json
###
POST http://localhost:3000/raid HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZ2l2ZW5fbmFtZSI6Ik5pZWxzIiwiY2l0eSI6Ik91ZGVuYWFyZGUiLCJuYmYiOjE2NTE0NTA3OTYsImV4cCI6MTY1MTQ1NDM5NiwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6MzAwMC8iLCJhdWQiOiJBZG1pbiJ9.0VyeB25tNoiAKqKEUA4P3iPGA5BVMvkVqBO1si1nuSE


{
    "Name" : "Sepulchur Of The First Ones Mythic",
    "Description" : "Minimum ILVL 255 / 4 set required",
    "Healer": {
        "HealerId": "626ebe44fe1dfe8b97e00d62"
    },
    "Tank":{
        "TankId": "626ebe51fe1dfe8b97e00d64"
    },
    "dps": {
        "DPSId": "626ebe32fe1dfe8b97e00d61"
    }
}
###
DELETE http://localhost:3000/raid/626ec4757738c146aacda8b1 HTTP/1.1
Content-Type: application/json
###
GET http://localhost:3000/raid/626edc4de266f3571dbf4f3e HTTP/1.1
Content-Type: application/json
###
GET http://localhost:3000/dps HTTP/1.1
Content-Type: application/json
###
GET http://localhost:3000/dps/damage/1001 HTTP/1.1
Content-Type: application/json
###
POST http://localhost:3000/authenticate HTTP/1.1
Content-Type: application/json

{
    "username": "niels",
    "password": "blepblep"
}